name: Experiment

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Print all environment variables
      run: env
